# This file is the template of cdn system configuration file.
# You can configure your cdn system by change the parameter according your requirement.
---
base:
  # listenPort is the port cdn server listens on.
  # default: 8003
  listenPort: 8003
  advertiseIP: __IP__

  # DownloadPort is the port for download files from cdn.
  # And you should start a file server firstly which listens on the download port.
  # default: 8001
  downloadPort: 8001

  # SystemReservedBandwidth is the network bandwidth reserved for system software.
  # default: 20 MB, in format of G(B)/g/M(B)/m/K(B)/k/B, pure number will also be parsed as Byte.
  systemReservedBandwidth: 20M

  # MaxBandwidth is the network bandwidth that cdn can use.
  # default: 200 MB, in format of G(B)/g/M(B)/m/K(B)/k/B, pure number will also be parsed as Byte.
  maxBandwidth: 1024M

  # Whether to enable profiler
  # default: false
  enableProfiler: false

  # FailAccessInterval is the interval time after failed to access the URL.
  # If a task failed to be downloaded from the source, it will not be retried in the time since the last failure.
  # default: 3m
  failAccessInterval: 3m

  # GCInitialDelay is the delay time from the start to the first GC execution.
  # default: 6s
  gcInitialDelay: 6s

  # GCMetaInterval is the interval time to execute GC meta.
  # default: 2m0s
  gcMetaInterval: 2m

  # gcStorageInterval is the interval time to execute GC storage.
  # default: 15s
  gcStorageInterval: 15s

  # TaskExpireTime when a task is not accessed within the taskExpireTime,
  # and it will be treated to be expired.
  # default: 3m0s
  taskExpireTime: 3m

  # StoragePattern is the pattern of storage policy, [disk/hybrid]
  storagePattern: disk

  # Console shows log on console
  console: false

plugins:
  storageDriver:
  - name: disk
    enable: true
    config:
      baseDir: /tmp/cdn
  storageManager:
  - name: disk
    enable: true
    config:
      gcInitialDelay: 5s
      gcInterval: 15s
      driverConfigs:
        disk:
          gcConfig:
            youngGCThreshold: 100G
            fullGCThreshold: 5G
            cleanRatio: 1
            intervalThreshold: 2h
