# This file is the template of scheduler configuration file.
# You can configure your scheduler by change the parameter according your requirement.

# scheduler policy configuration
scheduler:
  # abtest whether to open ab test
  # default: false
  abtest: false
  # aevaluator specify which evaluator is used when taskID suffix with _A
  # only take effect when abtest is true
  # default: ""
  aevaluator: ""
  # bevaluator specify which evaluator is used when taskID suffix with _B
  # only take effect when abtest is true
  # default: ""
  bevaluator: ""
  # workerNum is the number of goroutines that perform scheduling tasks
  # default:
  workerNum: 12
  # backSourceCount is the number of back-to-origin clients when the CDN is disable or unavailable
  # default: 3
  backSourceCount: 3
  # accessWindow is access interval window that can trigger CDN back to the source again
  # default: 3m
  accessWindow: 3m
  # candidateParentCount is number of candidate parent nodes
  # default: 10
  candidateParentCount: 10
  # scheduler is currently effective scheduling policy
  # default: basic
  scheduler: basic
  # cdnLoad is CDN host can provide the maximum upload load
  # default: 100
  cdnLoad: 100
  # clientLoad is client host can provide the maximum upload load
  # default: 10
  clientLoad: 10
  # openMonitor Whether to enable monitoring, currently only the current peer list status information is monitored
  # default: false
  openMonitor: false
  # gc metadata configuration
  gc:
    # peerGCInterval peer's gc interval
    peerGCInterval: 1m
    # peerTTL peer's TTL duration
    peerTTL: 10m
    # peerTTI peer's TTI duration
    peerTTI: 3m
    # taskGCInterval task's gc interval
    taskGCInterval: 1m
    # taskTTL task's TTL duration
    taskTTL: 10m
    # taskTTI task's TTI duration
    taskTTI: 3m

# server scheduler instance configuration
server:
  # ip
  # ip: 127.0.0.1
  # host
  # host: localhost
  # ListenPort is the ip and port scheduler server listens on.
  # default: 8002
  port: 8002

# dynamic data configuration
dynConfig:
  # dynamic data source type
  type: manager

# manager configuration
manager:
  # addr manager access address
  addr: 127.0.0.1:65003
  # schedulerClusterID cluster id to which scheduler instance belongs
  schedulerClusterID: 1
  # keepAlive keep alive configuration
  keepAlive:
    # interval
    interval: 5s

# host scheduler host configuration
host:
  # location is the location of scheduler instance
  location: ""
  # idc is the idc of scheduler instance
  idc: ""

# machinery async job configuration, see https://github.com/RichardKnop/machinery
job:
  # globalWorkerNum
  globalWorkerNum: 2
  # schedulerWorkerNum
  schedulerWorkerNum: 3
  # localWorkerNum
  localWorkerNum: 3
  # redis configuration
  redis:
    # host
    host: ""
    # port
    port: 6379
    # password
    password: ""
    # brokerDB
    brokerDB: ""
    # backendDB
    backendDB: ""

# Whether to disable CDN
# default: false
disableCDN: false

# Console shows log on console
# default: false
console: false

# Whether to enable debug level logger and enable pprof
# default: false
verbose: false

# listen port for pprof, only valid when the verbose option is true
# default is -1. If it is 0, pprof will use a random port.
pprofPort: -1

# jaeger endpoint url, like: http://jaeger.dragonfly.svc:14268/api/traces
# default: ""
jaeger: ""

# service name used in tracer
# default: dragonfly-scheduler
service-name: dragonfly-scheduler
