version: "3.9"
services:
  dfdaemon:
    image: dragonflyoss/dfdaemon:v2.0.1
    depends_on:
    - scheduler
    - cdn
    container_name: dfdaemon
    network_mode: host
    volumes:
    - /tmp/log/dragonfly:/var/log/dragonfly
    - ./config/dfget.yaml:/etc/dragonfly/dfget.yaml

  scheduler:
    image: dragonflyoss/scheduler:v2.0.1
    depends_on:
    - cdn
    container_name: scheduler
    network_mode: host
    volumes:
    - /tmp/log/dragonfly:/var/log/dragonfly
    - ./config/scheduler.yaml:/etc/dragonfly/scheduler.yaml
    - ./config/cdn.json:/opt/dragonfly/scheduler-cdn/cdn.json

  cdn:
    image: dragonflyoss/cdn:v2.0.1
    container_name: cdn
    network_mode: host
    volumes:
    - /tmp/log/dragonfly:/var/log/dragonfly
    - ./config/cdn.yaml:/etc/dragonfly/cdn.yaml
    - ./config/nginx.conf:/etc/nginx/nginx.conf
