name: CI

on:
  push:
    branches: [ main, release-* ]
  pull_request:
    branches: [ main, release-* ]

env:
  GO_VERSION: 1.15

jobs:
  lint:
    name: Lint
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Golangci lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40.1

  test:
    name: Test
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Unit tests
        run: sudo make test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          flags: unittests

  build:
    name: Build
    timeout-minutes: 20
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: make build
