name: Lint

on:
  push:
    branches: [ main, release-* ]
  pull_request:
    branches: [ main, release-* ]

env:
  GO_VERSION: 1.15

jobs:
  lint:
    name: Lint
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Golangci lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40.1
